import type { Metadata } from 'next';
import './globals.css';

import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import SessionProviderWrapper from '@/components/login/session/SessionProviderWrapper';
import { ToastProviders } from '@/components/ui/toast';
import QueryProviderWrapper from '@/components/providers/QueryProviderWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper session={session}>
          <ToastProviders>
            <QueryProviderWrapper>{children}</QueryProviderWrapper>
          </ToastProviders>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
