import type { Metadata } from 'next';
import './globals.css';

import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import SessionProviderWrapper from '@/components/login/session/SessionProviderWrapper';
import { ToastProviders } from '@/components/ui/toast';
import QueryProviderWrapper from '@/components/providers/QueryProviderWrapper';

import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'], // 减少字体体积
  display: 'swap',    // 确保文字始终可见
});

export const metadata: Metadata = {
  title: '江城缘',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="zh-CN" className={inter.className}>
      <body>
        <SessionProviderWrapper session={session}>
          <ToastProviders>
            <QueryProviderWrapper>{children}</QueryProviderWrapper>
          </ToastProviders>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
